export const COLUMNS = 4;
export const ROWS = 3;

export const MIN_VISIBILITY_DURATION_MS = 500;
export const MAX_VISIBILITY_DURATION_MS = 1000;

export const MIN_UNDERGROUND_DURATION_MS = 1000;
export const MAX_UNDERGROUND_DURATION_MS = 10000;
